language: php

sudo: false

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - hhvm

env:
  - HSTORE_EXT=no
  - HSTORE_EXT=yes

before_script:
  - if [[ ${TRAVIS_PHP_VERSION:0:1} != "7" && "$HSTORE_EXT" == "yes" ]]; then sh -c "cd ext/hstore5x && phpize && ./configure --enable-hstore && make && make install"; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:1} == "7" && "$HSTORE_EXT" == "yes" ]]; then sh -c "cd ext/hstore7x && phpize && ./configure --enable-hstore && make && make install"; fi
  - if [ "$HSTORE_EXT" == "yes" ]; then echo "extension=hstore.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`; fi

after_success:
  - "php tests/Benchmark.php"

before_install:
  # turn off XDebug
  - phpenv config-rm xdebug.ini || return 0

install:
  - composer --prefer-source install

matrix:
  fast_finish: true
  exclude:
    - php: hhvm
      env: HSTORE_EXT=yes
  allow_failures:
    - php: hhvm
