
doctrine:
    dbal:
        types:
            hstore: Cent\HStore\Doctrine\Types\HStoreType
        mapping_types:
            hstore: hstore

    orm:
        dql:
            string_functions:
                contains:         Cent\HStore\Doctrine\Query\ContainsFunction
                defined:          Cent\HStore\Doctrine\Query\DefinedFunction
                existsAny:        Cent\HStore\Doctrine\Query\ExistsAnyFunction
                fetchval:         Cent\HStore\Doctrine\Query\FetchvalFunction
                hstoreDifference: Cent\HStore\Doctrine\Query\HstoreDifferenceFunction
